version: "3.8"

services:
  client:
    build: ./example-frontend/.
    ports:
      - "5000:5000"
    depends_on:
      - server

  server:
    build: ./example-backend/.
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: "exercise2_7-redis-1"
      POSTGRES_HOST: "exercise2_7-db-1"

  redis:
    image: redis:7.2

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
